services:

# A static site deployment frontend application
- type: web
  name: adopt-a-neighbor-frontend-production
  env: static
  branch: master # optional (uses repo default)
  buildCommand: cd frontend; yarn; yarn test; yarn build
  staticPublishPath: frontend/build
  autoDeploy: true

# A Hapi web service for production
- type: web
  name: adopt-a-neighbor-api-production
  env: node
  plan: starter # optional
  numInstances: 1
  branch: master  # optional (uses repo default)
  healthCheckPath: /
  buildCommand: cd backend; yarn
  startCommand: cd backend; yarn start
  pullRequestPreviewsEnabled: true  # optional
  autoDeploy: true